export const state = {
  role: "organisation",
  profile: {
    name: "Alex Morgan",
    place: "Dordrecht",
    help: "survey",
    org: "South Holland",
    type: "municipality",
  },
  screen: "overview",
  site: 0,
  incidents: true,
  overlayTheme: "habitats",
  overlays: {
    habitat: true,
    wind: true,
    grid380: true,
    grid150: true,
    gridDist: true,
    cables: true,
    substations: true,
    solar: true,
    storage: true,
    demand: true,
    incidents: true,
  },
};
